source 'https://rubygems.org/'

gem 'sinatra'
gem 'pry' 
gem 'pg'
gem 'sinatra-activerecord'
gem 'bcrypt'
gem 'json'
gem 'sass'
gem 'sinatra-cross_origin'
gem 'rest-client'
gem 'mime-types'
gem 'netrc'
gem 'http-accept'
gem 'http-cookie'
gem 'rake'
